### ISSUE TITLE
Randomly Arranged Garage

### ISSUE THREAD

**Issue by RagingFire37** [Ray-Adams/NitroType-Garage-Editor#1]
The code works, but now every time I log into nitro type my cars are arranged randomly even when I went through all of them and put them in a specific order. What can I do to fix this?

**Comment by Ray-Adams** [comment]
@RagingFire37 Make sure that you are hitting the <kbd>Save Garage</kbd> button on the top right of the garage **after** you rearrange your cars. 

If you generated a lot of garage sections and have a lot of cars, there is a good chance you may have forgotten this crucial step (which I did during the initial stages of the script).
